name: basic-checks

on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Build the app
      run: npm run build

    - name: Run unit tests
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
